config/routes.rb
Rails.application.routes.draw do
    resources :sessions, only: [:new, :create, :destroy]
    resources :gossips do
      resources :comments
      resources :likes
  end
  resources :conversations do
    resources :messages
   end
  resources :contact
  resources :team
  resources :users
  resources :cities
  
  root to: 'gossips#index' 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  validates :title, length: { in: 3..14 }
  validates :content, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :gossip_to_tags
  has_many :tags, through: :gossip_to_tags
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
  include GossipsHelper
  before_action :require_login, only: [:new, :create, :edit, :destroy]


  def index
    @gossips = Gossip.all
    # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
  end

  def show
    @comments = Comment.all
    @gossip = Gossip.find(params[:id])
    # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
  end

  def new
    @gossip = Gossip.new
    # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
  end

  def create
  @gossip = Gossip.new(title: params[:title], content: params[:content], user: current_user)
  if @gossip.save
    flash[:success] = "Gossip created!"
    redirect_to root_path
  else
    render :new
  end
  end

  def edit
    @gossip = Gossip.find(params[:id]) 

    # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
  end

  def update
    @gossip = Gossip.find(params[:id])
    if @gossip.update(gossip_params)
      flash[:success] = 'The Gossip was successfully edited'
      redirect_to @gossip
    else
      render :edit
    end
  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    flash[:success] = 'The Gossip was successfully destroyed'
    redirect_to gossips_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def require_login
    unless session[:user_id]
      flash[:error] = "You must be logged in to access this section"
      redirect_to new_session_path # halts request cycle
    end
  end


end

app/helpers/gossips_helper.rb
module GossipsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def author
    User.find(gossip.user_id)
  end
end

app/views/gossips/edit.html.erb
<html>

    <% if @gossip.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <p>We couldn't edit the Gossip because :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>

<h1>Edit Gossip</h1>


<body>

<%= form_for @gossip do |f| %>
  <div >
  <label >Title </label>
  <%= f.text_field :title, class: 'form-control' %>
  <label >Content </label>
  <%= f.text_area :content, class: 'form-control' %>
</div>
<div>
  <button type="submit" class="btn btn-primary"> Edit </button>
</div>
<% end %>


</body>

</html>

app/views/gossips/index.html.erb
<% flash.each do |key, value| %>
<div class="alert alert-success" role="alert">
  <%= value %>
</div>
<% end %>

<body>
  <h1>The Gossip Project</h1>

<h2 style="padding-bottom: 80px">Welcome <% if current_user %> <%= current_user.first_name.capitalize %> <% end%> </h2>

<%= button_to "Create a new Gossip", "gossips/new", :id => "open-contacts-dialog-btn",
      :class => "btn btn-primary btn-lg", :method => :get %>

<div class="container" style="display: flex; flex-wrap: wrap; justify-content: space-around; padding-top: 100px">
<% @gossips.each do |gossip| %>
        <div class="card text-white bg-secondary mb-3" style="width: 20rem;">
        <div class="card-header"><%= User.find(gossip.user_id).first_name %>  <%= User.find(gossip.user_id).last_name %>  </div>
        <div class="card-body">
         <h4 class="card-title"> <%= link_to "#{gossip.title}", "gossips/#{gossip.id}" %> </h4>
      <div class="card-footer">Comments: <%= gossip.comments.count %>   
      
      <p><% if session[:user_id]%>
        <% pre_like = gossip.likes.find { |like| like.user_id == current_user.id} %>
                <% if pre_like %>
                    <%= button_to 'Unlike', gossip_like_path(gossip, pre_like), method: :delete %>
                <% else %>
                    <%= button_to 'Like', gossip_likes_path(gossip), method: :post %>
                <% end %>
                <% end %></p>
            <p><%= gossip.likes.count %> <%= (gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
          </div>
      
    </div>
  </div>
  <% end %>
  </div>


</body>
 
  

app/views/gossips/new.html.erb
<html>


<% flash.each do |key, value| %>
<div class="alert alert-success" role="alert">
  <%= value %>
</div>
<% end %>

<% if @gossip.errors.any? %>
<div class="alert alert-danger" role="alert">
  <p>We couldn't create the Gossip because :</p>
  <ul>
    <% @gossip.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<body>
  <h1 style="padding-bottom: 80px">New Gossip</h1>



  <!-- ... -->
  <%= form_tag url_for(action: 'create'), method: "post", class: "form" do %>

  <%= label_tag 'Title' %>
  <%= text_field_tag 'title'%>
  <br /> <br />

  <%= label_tag 'Content' %>
  <%= text_area_tag 'content'%>
  <br /> <br />


  <%= submit_tag "Create Gossip" %>



  <% end %>


  <!-- ... -->
</body>

</html>

app/views/gossips/show.html.erb
      
      <div class="jumbotron">
          <h1 class="display-3"><%=@gossip.title %> </h1>
          <p class="lead"> <%= @gossip.content %> </p>
          <hr class="my-4">
            <p><%= link_to "#{User.find(@gossip.user_id).first_name} #{User.find(@gossip.user_id).last_name}", "../users/#{@gossip.user_id}" %></p>
            <p><%= link_to User.find(@gossip.user_id).city.name, "../cities/#{User.find(@gossip.user_id).city_id}" %></p>
            <p><p><%= @gossip.likes.count %> <%= (@gossip.likes.count) == 1 ? 'Like' : 'Likes'%></p>
            <% if session[:user_id]%>
                    <% pre_like = @gossip.likes.find { |like| like.user_id == current_user.id} %>
                    <% if pre_like %>
                        <%= button_to 'Unlike', gossip_like_path(@gossip, pre_like), method: :delete %>
                    <% else %>
                        <%= button_to 'Like', gossip_likes_path(@gossip), method: :post %>
                    <% end %></p>
                <% if current_user.id == @gossip.user_id %> 
                  <%= link_to 'Edit', edit_gossip_path, class: 'btn btn-primary' %>
                  <%= link_to 'Delete', gossip_path(@gossip), method: :delete, class: 'btn btn-danger', data: { confirm: "Are you sure you want to delete the article?"} %>
                <%end%>
             <%end%>
              </p>
        </div>
      

        <ul class="list-group">
            <h2 class="list-group-item">Comments</h2> <br>
            <li><%= link_to 'New Comment', "/gossips/#{@gossip.id}/comments/new", class: 'btn btn-primary btn-sm' %></li> <br>
                <% @comments.each do |comment| %>
                <% if @gossip.id == comment.gossip_id %>
            <li class="list-group-item list-group-item-primary"><%= User.find(comment.user_id).first_name %> Commented : <br><%= comment.content %> 
              <p> <br>
                <% if session[:user_id]%>
                <% if current_user.id == @gossip.user_id || current_user.id == comment.user_id%> 
                <%= link_to 'Edit', "/gossips/#{@gossip.id}/comments/#{comment.id}/edit", class: 'btn btn-primary btn-sm' %>
                <%= link_to 'Delete', "/gossips/#{@gossip.id}/comments/#{comment.id}", method: :delete, class: 'btn btn-danger btn-sm', data: { confirm: "Are you sure you want to delete the article?"} %>
              <%end%>
              <%end%>
              </p>
            
            </li>
            <% end %>
            <% end %>
            </div>
          </ul>


  
          